// SERVER RESPONSE
const BAD_REQUEST_STATUS_CODE = 400;
const UNAUTHORIZED_REQUEST_STATUS_CODE = 401;
const CONFLICT_REQUEST_STATUS_CODE = 409;


// JWT
const CURRENT_DATE_IN_JWT_FORM = Math.floor(Date.now() / 1000);

export {
    BAD_REQUEST_STATUS_CODE,
    UNAUTHORIZED_REQUEST_STATUS_CODE,
    CURRENT_DATE_IN_JWT_FORM,
    CONFLICT_REQUEST_STATUS_CODE
}
