[package]
name = "packages"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
crossterm = "0.29.0"
dotenv = "0.15.0"
reqwest = "0.12.23"
termion = "4.0.5"
tokio = {version = "1.47.1", features = ["full"]}
tui = {version = "0.19.0", default-features = false, features = ["termion"]}
